### ISSUE TITLE
Как сделать без словаря?

### ISSUE THREAD

**Issue by ssdsv** [lmd-luxoft/lab-4-inheritance-ssdsv#2]
Павел, мне со словарём кажется более логичным и быстрым.
Другой вариант, который могу предложить, это хранить их просто списком в одной куче и по нему проходить с опросом стратегий с вопросом "ты этот тип можешь обработать?", чтобы только сама стратегия знала, кого она умеет обрабатывать.
Пока писал вопрос, нашёл вариант, который Вы скорее всего и имели в виду -- это с полиморфизмом: CanMove(Type,From,To).

**Comment by ssdsv** [comment]
Даже не так: GetStrategy(Type).

**Comment by paveltsytovich** [comment]
Да, тоже вариант, но это рефлекшн. Я бы посмотрел в сторону классческого наследвания. Стратегия оправдана, если у нас много других методов, а различия только в Move. Либо, тогда храните ссылку на стратегию в классе фигуры
